#!/usr/bin/python
## An application to parse IRC log files. The purpose is mainly to
## remember commit messages.
## Made by Arne Mejlholm (aaby@gentoo.org)

import time
import sys

version = '0.3.2'

class Output:
    """ class that handles all io """

    outputhtmlfile = 'output.html'
    outputxmlfile = 'output.xml'

    def formatCommit(self, string):
        """ method that handles formatting af a log string. """

        time = string[0:5]

        charnr = -1
        startchar = -1
        endchar = -1
        for char in string:
            charnr = charnr + 1
            if char == '<':
                startchar = charnr
            elif char == '>':
                endchar = charnr
        name = string[startchar+1:endchar]
        newname = name
        if name[0] == '@':
            newname = 'Op ' + name[1:]
        if name[0] == '+':
            newname = name[1:]

        action = string[endchar+2:(len(string)-1)]

        return [time, newname, action]

    def writeHtmlFile(self, dataobject):
         """ a method that writes a html file passed as an object. """

         file = open(Output.outputhtmlfile, 'w')
         f = file.write
         f('<html>\n')
         f('<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">\n')
         f('<head><title>\n')
         f(dataobject.title + '... Generated by AMLog version ' + version + '\n')
         f('</title></head>\n')
         f('<body bgcolor=' + dataobject.backgroundcolor + '>\n')
         f('<h1 align=center>' + dataobject.title + '</h1>\n')
         f('<h2 align=center>Channel summary</h2>\n')
         f('<p align=center>\n')
         f('Log from channel: ' + str(dataobject.channelname) + ' parsed on: ' + str(dataobject.date) + '<br>\n')
         f('The duration of the log file was: ' + str(dataobject.duration[0]) +
                                     ' day(s) ' + str(dataobject.duration[1]) +
                                  ' hours and ' + str(dataobject.duration[2]) + ' minutes<br>\n')
         f('The following people have been active: <br>\n')
         i = -1
         length = len(dataobject.listofnicks) -1
         for nick in dataobject.listofnicks:
            i = i + 1
            if i == 0:
                f(nick)
            elif i == length:
                f(' and ' +nick + '<br>\n')
            elif i % 7 == 0:
                f(', ' +nick + '<br>\n')
            else:
                f(', ' + nick)
                
         commitlenght = len(dataobject.commits)
         f('The has been a total of: <b>' + str(commitlenght) + ' commits.</b>\n')
         f('</p>\n')

         f('<h2 align=center>Commit details </h2>\n')
         f('<p align=center>\n')
         f('<table border=1>\n')
         f('<tr><td><b>Nick</b></td><td><b>Time</b></td><td><b>Action</b></td></tr>\n')
         for line in dataobject.commits:
                 list = self.formatCommit(line)
                 f('<tr><td>' + list[1] +'</td><td>' + list[0] + '</td><td>' + list[2] + '</td></tr>\n')

         f('</table>\n')
         f('</p>\n')

         f('<hr>\n')
         f('<p align=center>Generated by AMLog version ' + version + '</p>')
         f('</body>\n')
         f('</html>\n')
         file.close()

    def writeXMLFile(self, dataobject):
        """ a method that writes an xml file passed as an object. """        
        file = open(Output.outputxmlfile, 'w')
        f = file.write
        cf = ConfFile()
        f('<?xml version="1.0" encoding="'+cf.parseConfFileString('ENCODING')+'"?>\n')
        f('<?xml-stylesheet href="' + cf.parseConfFileString('XSLPATH') + '" type="text/xsl"?>\n')
        f('<!DOCTYPE guide SYSTEM "'+ cf.parseConfFileString('DTDPATH') +'">\n')
        f('<guide>\n')
        f('<title>' + dataobject.title + '</title>\n\n')
        f('<author title="Author">\n')
        f('  <mail link="aaby@gentoo.org">AMLog v.' + version + '</mail>\n')
        f('</author>\n\n')
        f('<version>1.0</version>\n')
        f('<date>' + dataobject.date + '</date>\n\n')
        f('<abstract>\n')
        f('  This document shows stats from ' + dataobject.channelname + '\n')
        f('</abstract>\n\n')
        f('<chapter>\n')        
        f('<title>Channel Summary</title>\n')
        f('<body>\n\n')
        f('<p>\n')
        f('  Log from channel: ' + dataobject.channelname + ' parsed on:' + dataobject.date + '\n')
        f('</p>\n\n')
        f('<p>\n')
        f('  The duration of the log file was: ' +  str(dataobject.duration[0]) +
                                    ' day(s) ' + str(dataobject.duration[1]) +
                                 ' hours and ' + str(dataobject.duration[2]) + ' minutes\n')
        f('</p>\n\n')
        f('<p>\n')
        f('  The following people have been active:\n')
        f('</p>\n')
        i = -1
        length = len(dataobject.listofnicks) -1
        f('<p>\n')
        f('  ')
        for nick in dataobject.listofnicks:
            i = i + 1
            if i == 0:
                f(nick)
            elif i == length:
                f(' and ' +nick + '\n')
            elif i % 7 == 0:
                f(', ' +nick + '\n</p>\n\n<p>\n')
            else:
                f(', ' + nick)
        f('</p>\n\n')
        f('<p>\n')
        commitlenght = len(dataobject.commits)
        f('  There has been a total of: <b>' + str(commitlenght) + ' commits</b>.\n')
        f('</p>\n\n')
        f('</body>\n')        
        f('</chapter>\n\n')
        f('<chapter>\n')        
        f('<title>Commit details</title>\n')
        f('<body>\n\n')
        
        f('<table>\n')

        f(' <tr>\n')
        f('  <th>Nick</th>\n')
        f('  <th>Time</th>\n')
        f('  <th>Action</th>\n')
        f(' </tr>\n\n')
        for line in dataobject.commits:
            list = self.formatCommit(line)
            f(' <tr>\n  <ti>' + list[1] +'</ti>\n  <ti>' + list[0] + '</ti>\n  <ti>' + list[2] + '</ti>\n </tr>\n')

        f('</table>\n\n')
        ### bottom
        f('</body>\n')        
        f('</chapter>\n')        
        f('</guide>\n')
        file.close()
        
class ConfFile:
    """ class that handles the configuration file"""

    conffile = 'amlog.conf'

    def readConfFile(self):
        """ a method that reads a config file """
        confs = []
        file = open(self.conffile, 'r')
        for line in file.readlines():
            for char in line:
                if char == '#':
                    break
                elif char == '\n':
                    break
                else:
                    confs.append(line)
                    break

        file.close()
        return confs

    def parseConfFileString(self, string):
        """ a method that searches throgh a log file. It recieves a string representing
        what to look for and returns what is after the equals sign. """
        returner = 'default'
        list = self.readConfFile()
        for line in list:
            variable = line[0:len(string)]
            if variable == string: 
                returner = line[(len(string)+1):(len(line)-1)]
                break
            else:
                returner = 'failure'
        return returner

class LogFile:
    """ class that handles reading the log file """

    cf = ConfFile()
    logfile = str(cf.parseConfFileString('LOGFILE'))

    def readLogFile(self):
        """ a method that reads the log file to be parsed. Returns a list
        of lines in the logfile. """
        log = []
        file = open(self.logfile, 'r')
        for line in file.readlines():
            log.append(line)
        file.close()
        return log
    
class DataFile:
    """ the main class that is manipulated with.
        Holds all the information that the html file should contain at the end """

    def getChannelName():
        lf = LogFile()
        list = lf.readLogFile()
        charnr = 0
        for line in list:
            for char in line:
                if line[charnr:charnr+10] == 'has joined':
                    return line[charnr+11:(len(line)-1)]
                else:
                    charnr = charnr +1

    def getDate():
        """ a method that makes a pretty data and time output """
        gmt = time.gmtime(time.time())
        fmt = '%a, %d %b %Y %H:%M:%S GMT'
        str = time.strftime(fmt, gmt)
        return str

    def getCommits(): 
        lf = LogFile()
        commits = []
        log = lf.readLogFile()
        for string in log:
            charnr = 0
            for char in string:
                if str(string[charnr:charnr+14]) == '.xml opdateret':
                    commits.append(string)
                    charnr = charnr +1
                else:
                    charnr = charnr +1
        return commits

    def getTitle():
        cf = ConfFile()
        title = cf.parseConfFileString('TITLE')
        return title

    def getActiveNicks():
        lf = LogFile()
        log = lf.readLogFile()
        listofnicks = []
        for string in log:
            charnr = -1
            startchar = -1
            endchar = -1
            for char in string:
                charnr = charnr + 1
                if char == '<':
                    startchar = charnr
                    continue
                elif char == '>':
                    endchar = charnr
                    break
            if '<' in string:
                name = string[startchar+1:endchar]
                if name[0] == '@':
                    newname = name[1:]
                if name[0] == '+':
                    newname = name[1:]
                if newname in listofnicks:
                    continue
                else:
                    listofnicks.append(newname)

        return listofnicks

    def getDurationTime():
        day = 0
        lf = LogFile()
        log = lf.readLogFile()
        for string in log:
            if string[0:3] == '---':
                if string[4:14] == 'Log opened':
                    starthr = string[26:28]
                    startmi = string[29:31]
                if string[4:15] == 'Day changed':
                    day = day + 1
            else:
                if string[2] == ':':
                    endhr = string[0:2]
                    endmi = string[3:5]
        hours = int(endhr) - int(starthr)
        min = int(endmi) - int(startmi)
        if min < 0:
            hours = hours - 1
            min = 60 +  min
        if hours < 0:
            day = day - 1
            hours = hours + 24
        duration = [day, hours, min]
        return duration
        
    backgroundcolor = 'white'
    title = getTitle()
    channelname = getChannelName()
    date = getDate()
    commits = getCommits()
    listofnicks = getActiveNicks()
    duration = getDurationTime()

def __main__():
    op = Output()
    data = DataFile()
    arguments = sys.argv
    if len(arguments) == 1:
        print 'Writing output XML file...'
        op.writeXMLFile(data)
        print '\tDone...'
    elif len(arguments) > 2:
        print 'Too many commandline arguments'
        exit
    elif arguments[1] == 'html':
        print 'Writing output HTML file...'
        op.writeHtmlFile(data)
        print '\tDone...'
    elif arguments[1] == 'xml':
        print 'Writing output XML file...'
        op.writeXMLFile(data)
        print '\tDone...'
    else:
        print 'No recognized commandline arguments'
    print 'Thank you for using AMLog'
    
__main__()
